### ISSUE TITLE
Use https for Icinga repository

### ISSUE THREAD

**Issue by tbauriedel** [Icinga/ansible-collection-icinga#323]
The [defaults](https://github.com/Icinga/ansible-collection-icinga/blob/main/roles/repos/defaults/main.yml) for the Icinga repository uses http instead of https.

**Comment by Donien** [comment]
Hey, we have already talked about this briefly.  
I thought about this some more.

> Ignoring the package server's redirect from HTTP to HTTPS here.

What does using HTTPS actually achieve in this case?  
Do packages really need to be encrypted on their way from the server to the target machine?

The content of the packages is verified using signatures.  
I get that we definitely **MUST** use HTTP**S** when integrating a subscription repository, since we do not want to pass credentials via HTTP.

Other than that I only see a (slight) overhead when using HTTPS.
